name: Automated API Tests with Newman

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman and HTML Extra Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Newman Tests with Data File
        run: |
          newman run "Reqres Auth Flow.postman_collection.json" \
            --folder "DataTests" \
            -d search_data.csv \
            -r cli,htmlextra \
            --reporter-htmlextra-export report.html

      - name: Upload Test Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-test-report
          path: report.html