name: API Functional & Performance Tests

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  functional-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: Run Newman Tests
        run: |
          mkdir -p public
          newman run "Reqres Auth Flow.postman_collection.json" \
            --folder "DataTests" \
            -d search_data.csv \
            -r cli,htmlextra \
            --reporter-htmlextra-export public/index.html

      - name: Deploy Functional Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

  performance-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup k6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 Load Test
        run: k6 run load_test.js

      - name: Upload k6 Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: k6-performance-report
          path: k6_summary.html