name: API Functional, Security & Performance Tests

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup k6
        uses: grafana/setup-k6-action@v1

      - name: Install Newman & Reporters
        run: npm install -g newman newman-reporter-htmlextra

      - name: Prepare Public Directory
        run: mkdir -p public

      - name: Run Functional Tests (Newman)
        continue-on-error: true
        run: newman run "Reqres Auth Flow.postman_collection.json" --folder "DataTests" -d search_data.csv -r cli,htmlextra --reporter-htmlextra-export public/functional.html

      - name: Run Security Tests (Newman)
        continue-on-error: true
        run: newman run "API Security Testing.postman_collection.json" -e staging.postman_environment.json \-r cli,htmlextra --reporter-htmlextra-export public/security.html

      - name: Run Performance Tests (k6)
        continue-on-error: true
        run: k6 run load_test.js

      - name: Move Reports & Portal to Public Folder
        run: |
          if [ -f k6_summary.html ]; then cp k6_summary.html public/k6.html; fi
          if [ -f index.html ]; then cp index.html public/index.html; fi
          ls -la public

      - name: Deploy All Reports to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
